[workspace]
members = [
    "reva",
    "reva_actix",
    "reva_axum",
    "reva_derive",
    "reva_escape",
    "reva_parser",
]

exclude = ["fuzz"]
resolver = "2"
default-members = [
    "reva",
    "reva_derive",
    "reva_escape",
    "reva_parser",
]
